### ISSUE TITLE
Node 14.0.0 - pg does not response

### ISSUE THREAD

**Issue by Edweis** [brianc/node-postgres#2180]
Running a postgres locally
```javascript
import { Pool } from 'pg';
const pool = new Pool({})

describe('check connexion', () => {
  it('should select 1', async () => {
    const result = await pg.query('SELECT 1 as hey');
    expect(result.rows[0]).toEqual({ hey: 1 });
  });
  afterAll(() => pg.end());
});
```
Fails with current node 14.0.0
Works on node 12.16.2.

**Comment by tarcisiobruni** [comment]
Same error with me. I made a downgrade to solve this until get better solution

**Comment by brianc** [comment]
What version of pg are you using? We fixed this in pg@8.0.3

https://github.com/brianc/node-postgres/pull/2171

**Comment by brianc** [comment]
This is fixed in pg@8.0.3.  If you see this happening `pg>=8.0.3` please feel free to re-open this issue.

**Comment by scott88lee** [comment]
Faced the same problem, ran the command 'npm update' and pg works now.

**Comment by kingsleyliao** [comment]
tfw when you spend 5 days on this and the fix was to upgrade... thanks for the fix and @edweis for reporting

**Comment by mateuspiresl** [comment]
Oh gosh. I lost 3 days on this problem because I thought it was related to networks in docker containers.
Solution worked.

**Comment by Romstar** [comment]
I'm still experiencing this with node 14.16.1 and pg 8.6. Any advice?

**Comment by charmander** [comment]
@Romstar Does it hang with any other queries? If so, it’s probably not the same issue. Please open a separate one with the full details.

**Comment by siddiq-rehman** [comment]
Facing same issue with 

/ $ node -v
v14.17.0
/ $ npm -v
6.14.13
/ require('pg/package.json').version
'8.6.0'


Any help would be appreciated

**Comment by charmander** [comment]
@siddiq-rehman If you’re on pg 8.6.0 it’s probably not the same issue, so please open a new issue with full details.

**Comment by kartik-pant-23** [comment]
@siddiq-rehman did you find any solution, facing exact same issue!

**Comment by rodrigoalvarez** [comment]
I had the same issue (no error) until I updated, but I'm getting this error now on the connect:
**const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);**
node version: 16.13.2
pg version: 8.7.1
