### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by klammbueddel** [brianc/node-postgres#314]
Hi brianc,
this is my first Bug report, so please don't blame me for bad style:)

I have an issue with loosing connections. This happens after upgrading to node v0.10.1. I used v.8x? before and it worked. I am developing with Windows 8.

Maybe this happens because the Garbage Collector was modified in the new release?
I wrote a simple mocha test that shows the problem.
    var pg = require('pg');

```
describe('pg', function(){
  this.timeout(65000);
  describe('connection', function() {
    it("should throw no error for 1 min", function(testDone) {

      pg.on("error", function(e){
        //"Error: read ECONNRESET" is thrown for me after 30sec
        testDone(e)
      });

      pg.connect("tcp://postgres:1234@localhost/postgres", function(err, client, done){
        client.query("select 'something'", function(err, result){
          done();
          if (err) return testDone (err);

          setTimeout(function(){
            testDone();
          }, 60000);
        });
      })
    });
  });
})
```

Debugging this lead me to the assumption, that it is caused by the garbage collector, that is trying to destroy the tcp socket used by the database, but maybe I am completly wrong with this.

**Comment by ivanric** [comment]
Hello boys brian forum and apologize for the inconvenience ... primaremante tell but a month I'm using the "pg" package ago, I worked well ... hize as stated in the documentation building a pool and applying it in the constructor configurations for connection to postgres; but then I got an error -> ECONNRESET on the console when attempting to connect to postgres and a consultation; now I am using Windows 10 x64, postgreSQL 9.5 and node v4.6.0, I would greatly appreciate some clarification'm going with this two weeks without finding answers.



This is the error console:

`error fetching client from pool identificasion { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`


This is the code and the connection:

*********************************************bd.js************************************************

`var pg=require('pg');

	var config = {
	  user: 'postgres', //env var: PGUSER
	  database: 'TallerII', //env var: PGDATABASE
	  password: 'postgres', //env var: PGPASSWORD
	  host: 'localhost', // Server hosting the postgres database
	  port: 5432, //env var: PGPORT
	  max: 100, // número máximo de clientes en la pool
	  idleTimeoutMillis: 30000, // how long a client is allowed to remain idle before being closed
	};

	 // esto inicializa un conjunto de conexiones
	 // que se mantendrá abierta las conexiones inactivas durante 30 segundos
	 // y establecer un límite de 10 clientes de inactividad máximo
	 //pol es un conjunto de clientes
	var pool = new pg.Pool(config);


	pool.on('error', function (err, client) {
	
	  console.error('idle client error', err.message, err.stack)
	})


//basedatos es una variable que exporta una funcion
module.exports.basedatos=pool;
`


******************************************************index.js*************************

`router.post('/Usuario/identificasion', function(req, res, next) {//aui se le asigna las rutas
  console.log(req.body.xlogin,'tb',req.body.xpassword);
		pool.connect(function(err, client, done) {
		  if(err) {
		    return console.error('error fetching client from pool identificasion', err);
		  }
		  client.query('SELECT * FROM DATOS WHERE(login=$1 and password=$2 and estado=1) ', [req.body.xlogin,req.body.xpassword],function(err,result){
				// console.log(result.rows.toString());
				done();
				if(err) {
					return console.error('Error de ejecución de consulta', err);
				}
				var JsonR= new Object();
				JsonR.status="resp";
				JsonR.valor=false;
				if (result.rows.length!=0) {
					// var ob=new Object();
					// ob=result.rows
					// console.log('esteobjeto',ob);
					// for (var i = 0; i < result.rows.length; i++) {
					// 	console.log('Eltamaño: '+result.rows.length)
					// 	console.log(result.rows[i])
					// }
					// console.log('EL usuario esta en la bd');
					console.log(true);
					JsonR["valor"]=true;
					req.session.usuario = result.rows[0];
					console.log(result.rows[0].login);
 				} else {
					// console.log('El usuario no esta en la bd')
					console.log(false)
					JsonR["valor"]=false;
				}


				// res.json(result.rows)
				console.log(JsonR);
				res.json(JsonR)

			});
		});
		pool.on('error', function (err, client) {
			console.error('idle client error', err.message, err.stack)
		})
  // res.render('ModalLogueo');
});`

**Comment by ivanric** [comment]
``router.post('/Usuario/identificasion', function(req, res, next) {//aui se le asigna las rutas
console.log(req.body.xlogin,'tb',req.body.xpassword);
pool.connect(function(err, client, done) {
if(err) {
return console.error('error fetching client from pool identificasion', err);
}
client.query('SELECT * FROM DATOS WHERE(login=$1 and password=$2 and estado=1) ', [req.body.xlogin,req.body.xpassword],function(err,result){
// console.log(result.rows.toString());
done();
if(err) {
return console.error('Error de ejecución de consulta', err);
}
var JsonR= new Object();
JsonR.status="resp";
JsonR.valor=false;
if (result.rows.length!=0) {
// var ob=new Object();
// ob=result.rows
// console.log('esteobjeto',ob);
// for (var i = 0; i < result.rows.length; i++) {
// console.log('Eltamaño: '+result.rows.length)
// console.log(result.rows[i])
// }
// console.log('EL usuario esta en la bd');
console.log(true);
JsonR["valor"]=true;
req.session.usuario = result.rows[0];
console.log(result.rows[0].login);
} else {
// console.log('El usuario no esta en la bd')
console.log(false)
JsonR["valor"]=false;
}

            // res.json(result.rows)
            console.log(JsonR);
            res.json(JsonR)

        });
    });
    pool.on('error', function (err, client) {
        console.error('idle client error', err.message, err.stack)
    })

// res.render('ModalLogueo');
});``

**Comment by ivanric** [comment]
Hello boys brian forum and apologize for the inconvenience ... primaremante tell but a month I'm using the "pg" package ago, I worked well ... hize as stated in the documentation building a pool and applying it in the constructor configurations for connection to postgres; but then I got an error -> ECONNRESET on the console when attempting to connect to postgres and a consultation; now I am using Windows 10 x64, postgreSQL 9.5 and node v4.6.0, I would greatly appreciate some clarification'm going with this two weeks without finding answers.



This is the error console.
`error fetching client from pool identificasion { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`

This is the code and the connection:

*********************************************bd.js************************************************

`var pg=require('pg');

	var config = {
	  user: 'postgres', //env var: PGUSER
	  database: 'TallerII', //env var: PGDATABASE
	  password: 'postgres', //env var: PGPASSWORD
	  host: 'localhost', // Server hosting the postgres database
	  port: 5432, //env var: PGPORT
	  max: 100, // número máximo de clientes en la pool
	  idleTimeoutMillis: 30000, // how long a client is allowed to remain idle before being closed
	};

	 // esto inicializa un conjunto de conexiones
	 // que se mantendrá abierta las conexiones inactivas durante 30 segundos
	 // y establecer un límite de 10 clientes de inactividad máximo
	 //pol es un conjunto de clientes
	var pool = new pg.Pool(config);


	pool.on('error', function (err, client) {
	
	  console.error('idle client error', err.message, err.stack)
	})


//basedatos es una variable que exporta una funcion
module.exports.basedatos=pool;
`


******************************************************index.js*************************

`var express = require('express');
var router = express.Router();//declarando un objeto router para ser mandado a la app
var session= require('express-session');
var pg=require('pg');
var bd=require('../bd.js');
var pool=bd.basedatos;

router.post('/Usuario/identificasion', function(req, res, next) {//aui se le asigna las rutas
  console.log(req.body.xlogin,'tb',req.body.xpassword);
		pool.connect(function(err, client, done) {
		  if(err) {
		    return console.error('error fetching client from pool identificasion', err);
		  }
		  client.query('SELECT * FROM DATOS WHERE(login=$1 and password=$2 and estado=1) ', [req.body.xlogin,req.body.xpassword],function(err,result){
				// console.log(result.rows.toString());
				done();
				if(err) {
					return console.error('Error de ejecución de consulta', err);
				}
				var JsonR= new Object();
				JsonR.status="resp";
				JsonR.valor=false;
				if (result.rows.length!=0) {
					// var ob=new Object();
					// ob=result.rows
					// console.log('esteobjeto',ob);
					// for (var i = 0; i < result.rows.length; i++) {
					// 	console.log('Eltamaño: '+result.rows.length)
					// 	console.log(result.rows[i])
					// }
					// console.log('EL usuario esta en la bd');
					console.log(true);
					JsonR["valor"]=true;
					req.session.usuario = result.rows[0];
					console.log(result.rows[0].login);
 				} else {
					// console.log('El usuario no esta en la bd')
					console.log(false)
					JsonR["valor"]=false;
				}


				// res.json(result.rows)
				console.log(JsonR);
				res.json(JsonR)

			});
		});
		pool.on('error', function (err, client) {
			console.error('idle client error', err.message, err.stack)
		})
  // res.render('ModalLogueo');
});`

**Comment by ivanric** [comment]
`
var express = require('express');
var router = express.Router();//declarando un objeto router para ser mandado a la app
var pg=require('pg');
var bd=require('../bd.js');
// var base=require('../pool.js');
var session= require('express-session');

var pool=bd.basedatos;
router.post('/Usuario/identificasion', function(req, res, next) {//aui se le asigna las rutas
  console.log(req.body.xlogin,'tb',req.body.xpassword);
		pool.connect(function(err, client, done) {
		  if(err) {
		    return console.error('error fetching client from pool identificasion', err);
		  }
		  client.query('SELECT * FROM DATOS WHERE(login=$1 and password=$2 and estado=1) ', [req.body.xlogin,req.body.xpassword],function(err,result){
				// console.log(result.rows.toString());
				done();
				if(err) {
					return console.error('Error de ejecución de consulta', err);
				}
				var JsonR= new Object();
				JsonR.status="resp";
				JsonR.valor=false;
				if (result.rows.length!=0) {
					// var ob=new Object();
					// ob=result.rows
					// console.log('esteobjeto',ob);
					// for (var i = 0; i < result.rows.length; i++) {
					// 	console.log('Eltamaño: '+result.rows.length)
					// 	console.log(result.rows[i])
					// }
					// console.log('EL usuario esta en la bd');
					console.log(true);
					JsonR["valor"]=true;
					req.session.usuario = result.rows[0];
					console.log(result.rows[0].login);
 				} else {
					// console.log('El usuario no esta en la bd')
					console.log(false)
					JsonR["valor"]=false;
				}


				// res.json(result.rows)
				console.log(JsonR);
				res.json(JsonR)

			});
		});
		pool.on('error', function (err, client) {
			console.error('idle client error', err.message, err.stack)
		})
  // res.render('ModalLogueo');
});

router.all('/inicio', function(req, res, next) {//aui se le asigna las rutas
	if (req.session.usuario!=null) {
		console.log('La sesion tiene un id:',req.session.usuario);
		var obj=req.session.usuario;
		console.log(obj.login);
		console.log(obj.password);
		console.log(obj.estado);
		console.log(obj.codusu);
		console.log("Entre como inicio");
		pool.connect(function(err, client, done) {
			if(err) {// si existe un error
				return console.error('ir a buscar error de cliente de la pool', err);
			}
			client.query('select * from menu', function(err, result) {

				res.render('inicio',{
					menus: result.rows
				});
				if(err) {
					return console.error('Error de ejecución de consulta', err);
				}
				done();
				console.log(result.rows);//nostrando datos por consola
				// var valor=result.rows;
				//output: 1
			});
		});
		pool.on('error', function (err, client) {
			console.error('idle client error', err.message, err.stack)
		})
	} else {
		res.redirect('/index')
	}
});
`

**Comment by ivanric** [comment]
`var express = require('express');
var router = express.Router();//declarando un objeto router para ser mandado a la app
var pg=require('pg');
var bd=require('../bd.js');
// var base=require('../pool.js');
var session= require('express-session');

var pool=bd.basedatos;
router.post('/Usuario/identificasion', function(req, res, next) {//aui se le asigna las rutas
  console.log(req.body.xlogin,'tb',req.body.xpassword);
		pool.connect(function(err, client, done) {
		  if(err) {
		    return console.error('error fetching client from pool identificasion', err);
		  }
		  client.query('SELECT * FROM DATOS WHERE(login=$1 and password=$2 and estado=1) ', [req.body.xlogin,req.body.xpassword],function(err,result){
				// console.log(result.rows.toString());
				done();
				if(err) {
					return console.error('Error de ejecución de consulta', err);
				}
				var JsonR= new Object();
				JsonR.status="resp";
				JsonR.valor=false;
				if (result.rows.length!=0) {
					// console.log('EL usuario esta en la bd');
					console.log(true);
					JsonR["valor"]=true;
					req.session.usuario = result.rows[0];
					console.log(result.rows[0].login);
 				} else {
					// console.log('El usuario no esta en la bd')
					console.log(false)
					JsonR["valor"]=false;
				}
				// res.json(result.rows)
				console.log(JsonR);
				res.json(JsonR)
			});
		});
		pool.on('error', function (err, client) {
			console.error('idle client error', err.message, err.stack)
		})
  // res.render('ModalLogueo');
});

router.all('/inicio', function(req, res, next) {//aui se le asigna las rutas
	if (req.session.usuario!=null) {
		console.log('La sesion tiene un id:',req.session.usuario);
		var obj=req.session.usuario;
		console.log(obj.login);
		console.log(obj.password);
		console.log(obj.estado);
		console.log(obj.codusu);
		console.log("Entre como inicio");
		pool.connect(function(err, client, done) {
			if(err) {// si existe un error
				return console.error('ir a buscar error de cliente de la pool', err);
			}
			client.query('select * from menu', function(err, result) {

				res.render('inicio',{
					menus: result.rows
				});
				if(err) {
					return console.error('Error de ejecución de consulta', err);
				}
				done();
				console.log(result.rows);//nostrando datos por consola
				// var valor=result.rows;
				//output: 1
			});
		});
		pool.on('error', function (err, client) {
			console.error('idle client error', err.message, err.stack)
		})
	} else {
		res.redirect('/index')
	}
});`

**Comment by reinert** [comment]
I still get this error when trying to connect in Windows 7 x64.

here's the log:
```js
acquire client begin
dispense() clients=1 available=0 info
createResource() - creating obj - count=1 min=0 max=10 verbose
connecting new client
client connection error: { Error: read ECONNRESET
    at exports._errnoException (util.js:1034:11)
    at TCP.onread (net.js:580:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
acquire client. error: { Error: read ECONNRESET
    at exports._errnoException (util.js:1034:11)
    at TCP.onread (net.js:580:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
pg.connect failed: Error: read ECONNRESET
dispense() clients=0 available=0 info
```
